service: lambda-contact-form-handler

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.STAGE}
  region: us-east-1
  environment:
    EMAIL: ${self:custom.secrets.EMAIL}
    CAPTCHA: ${self:custom.secrets.CAPTCHA}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
      Resource: '*'

functions:
  handleForm:
    handler: handler.handleForm
    events:
      - http:
          path: /
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            methods:
              - OPTIONS
              - POST
            allowCredentials: false
